#pragma once

namespace callbacks {
	void SkinUpdate( );
	void ForceFullUpdate( );
	void ToggleLeft();
	void ToggleRight();
	void ToggleBack();
	void ToggleForward();
	bool droppedwpnson();
	bool droppedglowewpaon();
	bool ammoon();
	bool boxon();
	bool nameon();
	bool weaponiconon();
	bool skeleton();
	bool outofpov();
	bool soundesp();
	bool lbytimeron();
	bool glowon();
	bool isbullettracer();
	bool islaseron();
	bool grenadeson();
	bool bombon();
	bool trajectoryon();
	bool peneton();
	void ToggleForceBodyAim();
	bool IsNightMode();
	bool isambient();
	void ToggleThirdPerson( );
	bool enemy_on();
	bool local_on();
	bool local_on_laser();
	bool enemy_on_laser();
	bool local_on_impacts();
	bool enemy_on_impacts();
	bool local_on_impacts2();
	bool ToggleFakeWalkOn( );
	bool retry_on( );
	void ToggleFakeLatency( );
	bool ToggleFakeLatencyOn();
	void ToggleSecondarayFakeLatency();
	bool ToggleSecondaryFakeLatencyOn();
	bool IsProjectiles();
	bool backgroundindicalphawhatever();
	bool autobuyon();
    void ToggleKillfeed( );
	void SaveHotkeys( );
	void ConfigLoad1( );
	void ConfigLoad2( );
	bool IsDelayShot();
	bool IsPFBOn();
	bool IsAstopOn();
	bool IsInAirAstop();
	void ConfigLoad3( );
	void ConfigLoad4( );
	void ConfigLoad5( );
	void ConfigLoad6( );
	void ConfigLoad( );
	void ConfigSave( );
	void emporium( );
	void retry( );
	
	bool IsHitmarker( );
	bool IsBaimHealth( );
	bool IsFovOn( );
	bool IsHitchanceOn( );
	bool IsAccuracyBoostOn();
	bool IsHitchancAireOn();
	bool IsPenetrationOn( );
	bool IsMultipointOn( );
	bool cjFIjfjciFjlohpoF();
	bool IsMultipointBodyOn( );

	bool IsAntiAimModeStand( );
	bool IsSwitchFakeBody();
	bool IsCustomBody();
	bool IsCustomTwist();
	bool IsUsingDistortion();
	bool HasStandYaw( );
	bool IsStandYawJitter( );
	bool IsStandYawRotate( );
	bool IsStandYawRnadom( );
	bool IsStandDirAuto( );
	bool IsStandDirCustom( );
	bool IsAntiAimModeWalk( );
	bool WalkHasYaw( );
	bool IsWalkYawJitter( );
	bool IsWalkYawRotate( );
	bool IsWalkYawRandom( );
	bool IsWalkDirAuto( );
	bool IsWalkDirCustom( );
	bool IsAntiAimModeAir( );
	bool AirHasYaw( );
	bool IsAirYawJitter( );
	bool IsAirYawRotate( );
	bool IsAirYawRandom( );
	bool IsAirDirAuto( );
	bool IsAirDirCustom( );
	bool IsFakeAntiAimRelative( );
	bool IsFakeAntiAimJitter( );
	
	bool IsFluctuateOn();

	bool landon();

	bool IsConfig1( );
	bool IsConfig2( );
	bool IsConfig3( );
	bool IsConfig4( );
	bool IsConfig5( );
	bool IsConfig6( );

	// weapon cfgs.
	bool DEAGLE( );
	bool ELITE( );
	bool FIVESEVEN( );
	bool GLOCK( );
	bool AK47( );
	bool AUG( );
	bool AWP( );
	bool FAMAS( );
	bool G3SG1( );
	bool GALIL( );
	bool M249( );
	bool M4A4( );
	bool MAC10( );
	bool P90( );
	bool UMP45( );
	bool XM1014( );
	bool BIZON( );
	bool MAG7( );
	bool NEGEV( );
	bool SAWEDOFF( );
	bool TEC9( );
	bool P2000( );
	bool MP7( );
	bool MP9( );
	bool NOVA( );
	bool P250( );
	bool SCAR20( );
	bool SG553( );
	bool SSG08( );
	bool M4A1S( );
	bool USPS( );
	bool CZ75A( );
	bool REVOLVER( );
	bool KNIFE_BAYONET( );
	bool KNIFE_FLIP( );
	bool KNIFE_GUT( );
	bool KNIFE_KARAMBIT( );
	bool KNIFE_M9_BAYONET( );
	bool KNIFE_HUNTSMAN( );
	bool KNIFE_FALCHION( );
	bool KNIFE_BOWIE( );
	bool KNIFE_BUTTERFLY( );
	bool KNIFE_SHADOW_DAGGERS( );
	bool IsOverrideDamage();

	bool IsLimitTarget();

	void ToggleDMG();
	bool ammpespon();
	bool IsChamsSelection0();
	bool LocalGlowChamsSelection();
	bool IsChamsSelection1();
	bool EnemyGlowChamsSelection();
	bool EnemyMetallicChamsSelection();
	bool IsChamsSelection2();
	bool IsChamsSelection3();
	bool IsChamsSelection4();
	bool IsChamsSelection5();
	bool IsChamsSelection6();
	bool FakeGlowChamsSelection();
}